name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "yanyubaby.eu.org"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "3628b986acf743d3a2836463fd826287"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://yanyubaby.eu.org"

# url to repo, displayed in index page
REPO = ""

# url to favicon
FAVICON = "https://ys.mihoyo.com/main/favicon.ico"

# the name displayed in TOS
TOS_MAINTAINER = "Genshin"

# the email displayed in TOS
TOS_MAIL = "xudong.zhong@mihoyo.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
